//! The vector family (x, y, z): generated by `wasmachine_macros::vectors!`,
//! plus the hand-written extras that don't fit the macro's uniform shape
//! (`Vector3d` rounding to block coords, geometric products, `Scale`/
//! `Velocity` algebra).

use super::ticks::Ticks;

wasmachine_macros::vectors! {
    /// General-purpose `f64` vector — the neutral hub of the family.
    pub struct Vector3d(f64);
    /// General-purpose `i64` vector (block coordinates and grids).
    pub struct Vector3i(i64);
    /// A point in space, relative to the animation origin.
    pub struct Position(f64);
    /// A displacement between two points.
    pub struct Offset(f64);
    /// Speed, in blocks per tick.
    pub struct Velocity(f64);
    /// Per-axis scale factor.
    pub struct Scale(f64);

    ops {
        Vector3d + Vector3d = Vector3d;
        Vector3d - Vector3d = Vector3d;
        Vector3i + Vector3i = Vector3i;
        Vector3i - Vector3i = Vector3i;
        Position + Offset = Position;
        Position - Offset = Position;
        Position - Position = Offset;
        Offset + Offset = Offset;
        Offset - Offset = Offset;
        Velocity + Velocity = Velocity;
        Velocity - Velocity = Velocity;
    }
    scale {
        Vector3d * f64;
        Offset * f64;
        Velocity * f64;
        Scale * f64;
        Vector3i * i64;
    }
    convert {
        Vector3d, Vector3i, Position, Offset, Velocity, Scale;
    }
}

impl Vector3d {
    /// Componentwise floor (differs from the `as`-cast `From` conversion,
    /// which truncates toward zero).
    pub fn floor(self) -> Vector3i {
        Vector3i::new(
            self.x.floor() as i64,
            self.y.floor() as i64,
            self.z.floor() as i64,
        )
    }

    pub fn round(self) -> Vector3i {
        Vector3i::new(
            self.x.round() as i64,
            self.y.round() as i64,
            self.z.round() as i64,
        )
    }

    pub fn ceil(self) -> Vector3i {
        Vector3i::new(
            self.x.ceil() as i64,
            self.y.ceil() as i64,
            self.z.ceil() as i64,
        )
    }

    /// Euclidean length.
    pub fn length(self) -> f64 {
        self.dot(self).sqrt()
    }

    /// Dot product.
    pub fn dot(self, rhs: Vector3d) -> f64 {
        self.x * rhs.x + self.y * rhs.y + self.z * rhs.z
    }

    /// Cross product (right-handed).
    pub fn cross(self, rhs: Vector3d) -> Vector3d {
        Vector3d::new(
            self.y * rhs.z - self.z * rhs.y,
            self.z * rhs.x - self.x * rhs.z,
            self.x * rhs.y - self.y * rhs.x,
        )
    }

    /// Unit vector in the same direction. Normalizing the zero vector has no
    /// meaningful direction, so it kills the animation rather than returning
    /// NaN.
    pub fn normalize(self) -> Vector3d {
        let len = self.length();
        assert!(len > 0.0, "cannot normalize a zero-length vector");
        self / len
    }
}

impl Offset {
    /// Euclidean length (distance covered).
    pub fn length(self) -> f64 {
        self.dot(self).sqrt()
    }

    /// Dot product.
    pub fn dot(self, rhs: Offset) -> f64 {
        self.x * rhs.x + self.y * rhs.y + self.z * rhs.z
    }
}

/// Component-wise; composing scales multiplies factors.
impl core::ops::Mul for Scale {
    type Output = Scale;
    fn mul(self, rhs: Scale) -> Scale {
        Scale::new(self.x * rhs.x, self.y * rhs.y, self.z * rhs.z)
    }
}

impl core::ops::MulAssign for Scale {
    fn mul_assign(&mut self, rhs: Scale) {
        *self = *self * rhs;
    }
}

/// Distance covered over a duration.
impl core::ops::Mul<Ticks> for Velocity {
    type Output = Offset;
    fn mul(self, t: Ticks) -> Offset {
        let ticks = t.count() as f64;
        Offset::new(self.x * ticks, self.y * ticks, self.z * ticks)
    }
}
